package pj;

import java.io.Serializable;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.List;

/**
 *  ###  Generated by Oracle JDeveloper 11g Release 1 11.1.1.6.38.61.92 - Wed Feb 01 10:59:21 PST 2012.  ###
 */

public class Dept implements Serializable {

    /**Map empCollection <-> pj.Emp
     * @associates <{pj.Emp}>
     */
    private List<Emp> empCollection;
    private BigDecimal deptno;
    private String dname;
    private String loc;

    public Dept(BigDecimal deptno, String dname, String loc) {
        this.deptno = deptno;
        this.empCollection = new ArrayList();
        this.dname = dname;
        this.loc = loc;
    }

    public Dept() {
        this.empCollection = new ArrayList();
    }

    public void addEmp(Emp anEmp) {
        this.empCollection.add(anEmp);
        anEmp.setDeptno(this);
    }

    public void addEmp(int index, Emp anEmp) {
        this.empCollection.add(index, anEmp);
        anEmp.setDeptno(this);
    }

    public BigDecimal getDeptno() {
        return this.deptno;
    }

    public String getDname() {
        return this.dname;
    }

    public List<Emp> getEmpCollection() {
        return this.empCollection;
    }

    public String getLoc() {
        return this.loc;
    }

    public void removeEmp(Emp anEmp) {
        this.empCollection.remove(anEmp);
        anEmp.setDeptno(null);
    }

    public void setDeptno(BigDecimal deptno) {
        this.deptno = deptno;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }

    public void setEmpCollection(List<Emp> empCollection) {
        this.empCollection = empCollection;
    }

    public void setLoc(String loc) {
        this.loc = loc;
    }

}
